# Generated by Django 5.1.6 on 2025-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(default=None, help_text='When the exam ends'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(default=None, help_text='When the exam begins'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='hall',
            field=models.CharField(max_length=100),
        ),
    ]
